- name: Run timesrv
  hosts: "{{ ip }}"
  become: yes
  vars:
    ansible_user: root
    ansible_ssh_pass: root
    ansible_become: false
    interface: eth0

  tasks:
    - name: run fastapi
      ansible.builtin.shell: |
        nohup fastapi run ./timesrv/main.py --port {{ app_port }} --host 0.0.0.0 > /root/logfile.log 2>&1 &
      args:
        chdir: /root/wso
      environment:
        WSOTIMESRV_MANAGER_ADDRESS: "{{ wsotimesrv_manager_address }}"
        WSOTIMESRV_TOKEN: "{{ wsotimesrv_token }}"
      async: 1
      poll: 0
