- name: Run timesrv
  hosts: "{{ ip }}"
  become: yes
  vars:
    ansible_user: root
    ansible_ssh_pass: root
    ansible_become: false
    interface: eth0

  tasks:
    - name: Copy nginx.conf to the server
      copy:
        src: ./nginx.conf
        dest: /etc/nginx/nginx.conf
        backup: yes

    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded
