- name: Run timesrv
  hosts: "{{ ip }}"
  become: yes
  vars:
    ansible_user: root
    ansible_ssh_pass: root
    ansible_become: false
    interface: eth0

  tasks:
    - name: Copy nginx.conf to the server
      copy:
        src: ./nginx.conf
        dest: /etc/nginx/nginx.conf
        backup: yes

    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded

    - name: run heart
      ansible.builtin.shell: |
        nohup python3 -m heart.main > /root/logfile.log 2>&1 &
      args:
        chdir: /root/wso
      environment:
        WSOHEART_MANAGER_ADDRESS: "{{ wsotimesrv_manager_address }}"
        WSOHEART_TOKEN: "{{ wsotimesrv_token }}"
      async: 1
      poll: 0
